agent_authorizer: 
api_password: 
api_url: 
api_username: 
backup_directory: 
ead_3_schema: 
ead_3_transformation: 
ead_log_path: 
exclusions:
input_csv:
input_dir: 
local_sql_database: 
local_sql_hostname: 
local_sql_password: 
local_sql_port: 
local_sql_username: 
manifest_path: 
output_dir: 
output_file: 
path_to_key:
saxon_path: 
sql_database:
sql_hostname: 
sql_password:
sql_port:
sql_username:
ssh_host: 
ssh_port: 
ssh_user: 
transformation_errors:
validation_errors: 
