agent_authorizer: 
api_password: Fluffernutter27
api_url: https://testarchivesspace.library.yale.edu/api
api_username: amd243
backup_directory: /Users/aliciadetelich/Dropbox/git/aspace_tools/data/backups
ead_3_schema: 
ead_3_transformation: 
ead_log_path: 
exclusions:
input_csv: /Users/aliciadetelich/Dropbox/git/aspace_tools/data/inputs/sample_resource_uris.csv
input_dir: 
local_sql_database: 
local_sql_hostname: 
local_sql_password: 
local_sql_port: 
local_sql_username: 
manifest_path: 
output_dir: 
output_file: 
path_to_key:
saxon_path: 
sql_database:
sql_hostname: 
sql_password:
sql_port:
sql_username:
ssh_host: 
ssh_port: 
ssh_user: 
transformation_errors:
validation_errors: 
